trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python39:
      python.version: '3.9'

steps:
  - script: |
      pip install wheel
      pip install twine
    displayName: 'Install library with dependencies'

  - script: |
      python ./setup.py bdist_wheel
    displayName: 'Artifact creation'

  - task: TwineAuthenticate@1
    displayName: 'Twine Authenticate'
    inputs:
      pythonUploadServiceConnection: 'PyPI_aioconnect'

  - script: |
      python -m twine upload --skip-existing --verbose --repository "aioconnect" --config-file $(PYPIRC_PATH) dist/*.whl
    displayName: 'Publish to PyPi through Twine'
