# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - dev
    always: true

trigger:
  - dev

pool:
  vmImage: "ubuntu-latest"
strategy:
  matrix:
    Python37:
      python.version: "3.7"
    Python38:
      python.version: "3.8"

steps:
  - script: |
      pip install twine
    displayName: "Pip install twine"
    env:
      SEBASTIAN_SZILVAS_AIO_IMPACT: $(sebastian-szilvas-aio-impact)
      displayName: "Set tokens as environment tokens"

  - task: TwineAuthenticate@1
    inputs:
      externalFeeds: "PyPI"

  - script: "twine upload -r {PyPI/aioconnect} --config-file $(PYPIRC_PATH) {aioconnect}"

  - task: UsePythonVersion@0
    inputs:
      versionSpec: "$(python.version)"
    displayName: "Use Python $(python.version)"

  - script: |
      python -m pip install --upgrade pip
      pip install -e ./aioconnect/
    displayName: "Install library with dependencies"

  - task: AzureKeyVault@1
    inputs:
      azureSubscription: "aioneersMainSubscription(603f9c05-0a2a-4daa-914d-8242a3a4beb8)"
      KeyVaultName: "aio-data-science-key"
      SecretsFilter: "*"
      RunAsPreJob: false

  - script: |
      pip install pytest pytest-azurepipelines
      pytest
    displayName: "Pytest. Everything. No skips allowed"
    env:
      SEBASTIAN_SZILVAS_AIO_IMPACT: $(sebastian-szilvas-aio-impact)
      displayName: "Set tokens as environment tokens"
